# Default values for cert-manager-istio-csr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-istio-csr
  tag: v0.0.1-alpha.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

agent:
  logLevel: 1 # 1-5
  readinessProbe:
    port: 6060
    path: "/readyz"

  servingAddress: 0.0.0.0
  servingPort: 6443

  rootCAConfigMapName: istio-ca-root-cert
  certificateDuration: 24h

certificate:
  namespace: istio-system
  group: cert-manager.io
  kind: Issuer
  name: istio-ca
  maxDuration: 24h
  preserveCertificateRequests: false

  rootCA: #|
       #MyCACertificate

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  #
